version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
    ports:
      - "5430:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitvolume:/var/lib/rabbitmq
    networks:
      - lan
volumes:
  pgvolume:
  rabbitvolume:
networks:
  lan:
