spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/data
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
reserve-court:
  security:
    backend-domain: http://kni.prz.edu.pl:47453
    socket-domain: http://kni.prz.edu.pl:47454
    allowedOrigins:
      - http://localhost:3000
      - http://localhost:8080
      - http://192.168.100.204:3000