name: Java CI with Maven

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Write SSH keys
      run: |
            which ssh-agent || (sudo apk update && sudo apk add openssh-client)
            which rsync || (sudo apk update && sudo apk add rsync)
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/private.key
            touch ~/.ssh/known_hosts
            chmod 600 ~/.ssh/private.key
            echo -e "${{ vars.MALWINA_SSH_SECRET }}" | tr -d '\r' > ~/.ssh/private.key
            
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/private.key
    
    - name: Update repo
      run: |
        ssh -p 47455 root@kni.prz.edu.pl << EOF
        cd ../home/reserve/reServeCourt_backend
        git pull
        cd ..
        docker compose up -d
        EOF
